version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "9999:9999"
    environment:
      NODE_ENV: production
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium"
    volumes:
      - .:/app
    restart: unless-stopped
