# fly.toml app configuration file generated for nodejs-phantom-chromium on 2024-09-20T16:39:07-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nodejs-phantom-chromium'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 9999
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
